export default [
  { title: 'Blazing Fury', seen: true, category: 'Action' },
  { title: 'Breakaway', seen: true, category: 'Action' },
  { title: 'Breaking the Chains', seen: false, category: 'Drama' },
  { title: 'Broken Promises', seen: false, category: 'Drama' },
  { title: 'Chasing Shadows', seen: true, category: 'Action' },
  { title: 'Hearts Unfold', seen: false, category: 'Drama' },
  { title: 'Laugh Till Dawn', seen: true, category: 'Commedy' },
  { title: 'Laughing Matters', seen: true, category: 'Comedy' },
  { title: 'Laughter Avenue', seen: false, category: 'Comedy' },
  { title: 'Laughter in the Rain', seen: true, category: 'Comedy' },
  { title: 'Redemption Path', seen: false, category: 'Drama' },
  { title: 'Rush Hour Riot', seen: false, category: 'Action' },
  { title: "Shadow's Edge", seen: true, category: 'Drama' },
  { title: 'The Last Horizon', seen: false, category: 'Drama' },
  { title: 'The Last Stand', seen: true, category: 'Action' },
  { title: 'The Midnight Escape', seen: false, category: 'Action' },
  { title: 'The Silent Echo', seen: true, category: 'Drama' },
  { title: 'The Silent Struggle', seen: true, category: 'Drama' },
  { title: 'Velocity Chasers', seen: false, category: 'Action' }
]